apiVersion: v2
name: rabbitmq-agent
description: Demo Kubernetes HPA based on RabbitMQ Queue (Prometheus/VictoriaMetrics/KEDA)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - rabbitmq
  - hpa
  - keda
  - prometheus
  - victoriametrics
  - autoscaling
home: https://github.com/mrlioncub/k8s-hpa-rabbitmq-demo
sources:
  - https://github.com/mrlioncub/k8s-hpa-rabbitmq-demo
maintainers:
  - name: mrlioncub
    url: https://github.com/mrlioncub
