prometheus:
  url: http://prometheus-server.k8-hpa-rabbitmq-demo.svc.cluster.local
  port: 80

logLevel: 6

rules:
  default: false
  custom:
  - seriesQuery: 'rabbitmq_queue_messages{kubernetes_namespace!="",kubernetes_pod_name!="",queue="task_queue"}'
    resources:
      overrides:
        kubernetes_namespace: {resource: "namespace"}
        kubernetes_pod_name: {resource: "pod"}
    metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,queue="task_queue"}) by (<<.GroupBy>>)
