fullnameOverride: "rabbitmq-server"

auth:
  username: guest
  password: guest

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "15692"
  prometheus.io/path: "/metrics"

metrics:
  enabled: true

singleNode:
  persistence:
    enabled: false
